c_compiler:
  - gcc      # [linux]
  - clang    # [osx]
c_compiler_version:
  - 7        # [linux]
  - 9        # [osx]
cxx_compiler:
  - gxx      # [linux]
  - clangxx  # [osx]
cxx_compiler_version:
  - 7        # [linux]
  - 9        # [osx]

# macOS related settings
macos_min_version:
  - 10.14                      # [osx]
macos_machine:
  - x86_64-apple-darwin18.7.0  # [osx]
MACOSX_DEPLOYMENT_TARGET:
  - 10.14                      # [osx]

# Pinned versions
arrow_cpp:
  - 3.0
aws_sdk_cpp:
  - 1.8
cmake:
  - 3.15
doxygen:
  - 1.8
libiconv:
  - 1.15
libopencv:
  - 4.2
libprotobuf:
  - 3.13
python:
  - 3.6
  - 3.7
  - 3.8
tbb_devel:
  - 2019.8
zlib:
  - 1.2
